# Generated by Django 3.2.5 on 2021-08-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouphasmember',
            old_name='member',
            new_name='name',
        ),
    ]
