# Generated by Django 3.2.5 on 2021-07-25 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProfilesDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New party', max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_leader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='profilehashero',
            name='times_played',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='GroupHasMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('role', models.CharField(choices=[('dps', 'DPS'), ('healer', 'Healer'), ('tank', 'tank')], default=('dps', 'DPS'), max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfilesDB.group')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfilesDB.profilehashero')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='ProfilesDB.GroupHasMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
