# Generated by Django 3.2.5 on 2021-07-26 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProfilesDB', '0005_alter_grouphasmember_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grouphasmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ProfilesDB.group'),
        ),
        migrations.AlterField(
            model_name='grouphasmember',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ProfilesDB.profilehashero'),
        ),
        migrations.AlterField(
            model_name='grouphasmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
