# Generated by Django 3.2.5 on 2021-07-26 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProfilesDB', '0007_auto_20210726_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, through='ProfilesDB.GroupHasMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grouphasmember',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ProfilesDB.profilehashero'),
        ),
        migrations.AlterField(
            model_name='grouphasmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
