# Generated by Django 3.2.5 on 2021-07-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='no description', max_length=500)),
                ('avatar', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('rarity', models.IntegerField(choices=[(1, 'Common'), (2, 'Uncommon'), (3, 'Rare'), (4, 'Epic'), (5, 'Artifact'), (6, 'Mythic')], default=(1, 'Common'))),
                ('ardor', models.IntegerField(choices=[(5, 'Common'), (10, 'Uncommon'), (15, 'Rare'), (25, 'Epic'), (50, 'Artifact'), (100, 'Mythic')], default=(5, 'Common'))),
                ('rarity_html_tag', models.CharField(default='common', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='no description', max_length=500)),
                ('avatar', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='no description', max_length=500)),
                ('avatar', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.IntegerField(default=1)),
                ('health', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('mana', models.IntegerField(default=0)),
                ('armor', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('spell', models.IntegerField(default=0)),
                ('slot', models.IntegerField(blank=True, choices=[(1, 'weapon'), (2, 'body'), (3, 'trinket'), (None, 'None')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='no description', max_length=500)),
                ('base_health', models.IntegerField(default=1)),
                ('base_defense', models.IntegerField(default=1)),
                ('base_mana', models.IntegerField(default=1)),
                ('base_armor', models.IntegerField(default=0)),
                ('avatar', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.IntegerField(choices=[(1, 'dps'), (2, 'healer'), (3, 'tank')], default=1)),
                ('armor_type', models.CharField(choices=[('L', 'light'), ('M', 'Medium'), ('H', 'heavy')], default=('L', 'light'), max_length=2)),
            ],
        ),
    ]
