# Generated by Django 3.2.5 on 2021-07-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='ardor',
            field=models.IntegerField(choices=[(5, 'Common'), (10, 'Uncommon'), (15, 'Rare'), (25, 'Epic'), (50, 'Artifact'), (100, 'Mythic')], default=(5, 'Common')),
        ),
    ]
