# Generated by Django 3.2.5 on 2021-07-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_achievement_ardor'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='avatar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
