# Generated by Django 3.2.5 on 2021-07-21 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0002_profile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ardor',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours_played', models.IntegerField(default=0)),
                ('total_games_played', models.IntegerField(default=0)),
                ('total_ardor_points', models.IntegerField(default=0)),
                ('dice_rolled', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
