# Generated by Django 3.2.5 on 2021-07-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_achievement_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='rarity_html_tag',
            field=models.CharField(default='common', max_length=15),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='avatar',
            field=models.CharField(max_length=200),
        ),
    ]
