# Generated by Django 3.2.5 on 2021-07-21 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210722_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='dice_rolled',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_ardor_points',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_hours_played',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SoloData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0)),
                ('floors_passed', models.BigIntegerField(default=0)),
                ('monsters_killed', models.BigIntegerField(default=0)),
                ('max_floor_normal', models.IntegerField(default=0)),
                ('max_floor_chaos', models.IntegerField(default=0)),
                ('statistics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.statistics')),
            ],
        ),
    ]
