# Generated by Django 3.2.5 on 2021-07-21 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20210722_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solodata',
            old_name='statistics',
            new_name='statistics_link',
        ),
        migrations.AddField(
            model_name='statistics',
            name='solo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.solodata'),
        ),
    ]
