# Generated by Django 3.2.5 on 2021-07-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameObjectsDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dice',
            name='avatar',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='avatar',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
