# Generated by Django 3.2.5 on 2021-07-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameObjectsDB', '0002_auto_20210724_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='armor_type',
            field=models.CharField(choices=[('L', 'light'), ('M', 'Medium'), ('H', 'heavy')], default=('L', 'light'), max_length=2),
        ),
        migrations.AddField(
            model_name='hero',
            name='role',
            field=models.IntegerField(choices=[(1, 'dps'), (2, 'healer'), (3, 'tank')], default=1),
        ),
    ]
