# Generated by Django 3.2.5 on 2021-07-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameObjectsDB', '0003_auto_20210724_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='base_armor',
            field=models.IntegerField(default=0),
        ),
    ]
